#ifndef MATRIX_HPP
#define MATRIX_HPP

#include <cassert>
#include <cstddef>
#include <stdexcept>
#include <vector>

template <typename T>
using Vector2D = std::vector<std::vector<T>>;

/**
 * @class Matrix
 * @brief A simple 2D matrix container based on vector-of-vector representation.
 * @tparam T Type of elements stored in the matrix.
 */
template <typename T>
class Matrix
{
public:
    /**
     * @brief Default constructor.
     * Creates an empty 0x0 matrix.
     */
    Matrix(): Matrix(0, 0)
    {}

    /**
     * @brief Constructs a matix with given dimensions.
     * @param rows Number of rows.
     * @param cols Number of columns.
     */
    Matrix(std::size_t rows, std::size_t cols)
        : m_rows(rows)
        , m_cols(cols)
        , m_data(m_rows, std::vector<T>(m_cols))
    {}

    /**
     * @brief Defaulted copy constructor (generated by compiler).
     * std::size_t is trivially copyable and
     * std::vector provides deep copy semantics
     * (Rule of 0 applies)
     */
    Matrix(const Matrix&) = default;

    /**
     * @brief Defaulted move constructor (generated by compiler).
     * No need custom move behavior because of
     * compiler-generated implementation performs member-wise move.
     * std::vector already supports efficient move semantics.
     */
    Matrix(Matrix&&) = default;

    /**
     * @brief Row access operator.
     * Provides access to a specific row.
     * @param row Row index.
     * @return Return reference to the row vector.
     */
    std::vector<T>& operator[](std::size_t row)
    {
        assert(row < m_rows && "Invalid row index!");
        return m_data[row];
    }

    /**
     * @brief Const version of Row access operator.
     */
    const std::vector<T>& operator[](std::size_t row) const
    {
        assert(row < m_rows && "Invalid row index!");
        return m_data[row];
    }

    /**
     * @brief Matrix multiplication operator.
     * Computes the product of two matrices.
     * @param m Right-hand side matrix.
     * @return Resulting matrix of size (rows x m.cols).
     */
    Matrix<T> operator*(const Matrix<T>& m)
    {
        assert(getCols() == m.getRows() && "Matrix multiplication dimension mismatch!");
        std::size_t in = getCols();
        std::size_t rows = getRows();
        std::size_t cols = m.getCols();
        Matrix<T> res(rows, cols);
        for (std::size_t i = 0; i < rows; ++i) {
            for (std::size_t j = 0; j < cols; ++j) {
                T sum{};
                for (std::size_t k = 0; k < in; ++k) {
                    sum += m_data[i][k] * m[k][j];
                }
                res[i][j] = sum;
            }
        }
        return res;
    }

    /**
    * @brief Returns a transposed copy of the matrix.
    *
    * @return Matrix where rows and columns are swapped.
    */
    Matrix<T> transposed() const
    {
        std::size_t rows = getRows();
        std::size_t cols = getCols();
        Matrix<T> t(cols, rows);
        for (std::size_t i = 0; i < rows; ++i) {
            for (std::size_t j = 0; j < cols; ++j) {
                t[j][i] = m_data[i][j];
            }
        }
        return t;
    }

    /**
     * @brief Retruns number of rows.
     */
    const std::size_t getRows() const
    {
        return m_rows;
    }

    /**
     * @brief Retruns number of columns.
     */
    const std::size_t getCols() const
    {
        return m_cols;
    }

private:
    std::size_t m_rows;
    std::size_t m_cols;
    Vector2D<T> m_data;
};

#endif
